version: "2"

issues:
  max-same-issues: 0 # show all issues
  max-issues-per-linter: 0 # show all issues

formatters:
  default: all

linters:
  default: all
  disable:
    - cyclop # don't care about cyclomatic complexity
    - depguard # don't want to restrict imports
    - exhaustruct # redundant to write all struct fields
    - funlen # don't care about function length
    - godox # want to use TODO comments
    - mnd # want to use magic numbers
    - nestif # don't care about the complexity of nested if statements
    - nlreturn # don't want to insert a newline before return statement
    - noinlineerr # want to use inline error
    - varnamelen # don't care about variable name length
    - wrapcheck # don't want to wrap every error
    - wsl # don't want to restrict when to insert a new line
    - wsl_v5 # don't want to restrict when to insert a new line
  settings:
    govet:
      enable-all: true
      disable:
        - shadow # want to shadow err
    nolintlint: # stricter
      require-explanation: true
      require-specific: true
    perfsprint: # stricter
      strconcat: false
    staticcheck: # stricter
      checks:
        - all
    revive:
      enable-all-rules: true
      rules:
        - name: package-comments
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: function-length
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: add-constant
          disabled: true
        - name: enforce-switch-style
          disabled: true
  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - lll # some test cases are long
          - paralleltest # false positives
